apiVersion: v1
kind: Namespace
metadata:
  name: qperf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qperfall
  namespace: qperf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-creator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create","delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-creator-binding
subjects:
- kind: ServiceAccount
  name: qperfall
  namespace: qperf
roleRef:
  kind: ClusterRole
  name: namespace-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: qperf
  name: qperf-creator
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create","delete"]
- apiGroups: ["apps"]
  resources: ["daemonsets/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec","pods"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qperf-creator-binding
  namespace: qperf
subjects:
- kind: ServiceAccount
  name: qperfall
  namespace: qperf
roleRef:
  kind: Role
  name: qperf-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qperfall
  namespace: qperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qperfall
  template:
    metadata:
      labels:
        app: qperfall
    spec:
      serviceAccountName: qperfall
      containers:
      - name: qperfall
        image: docker.io/maitaba/qperfall:latest